/*
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ContractStandaloneSetup extends ContractStandaloneSetupGenerated {

	public static void doSetup() {
		new ContractStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
