/*
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractContractScopeProvider extends DelegatingScopeProvider {
}
