/**
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.generator;

import lsi.us.es.mis.xtext.contract.Attribute;
import lsi.us.es.mis.xtext.contract.Contract;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FireflyInterfaceGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    Contract contract = ((Contract) _head);
    String _name = contract.getName();
    String _plus = (_name + ".json");
    fsa.generateFile(_plus, this.toFireflyInterface(contract));
  }
  
  public String toFireflyInterface(final Contract contract) {
    final String name = contract.getName();
    final String version = contract.getVersion();
    String methods = this.defineMethods(contract);
    String events = this.defineEvents(contract);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"name\": \"");
    _builder.append(name, "    ");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"version\":  \"");
    _builder.append(version, "    ");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("\"methods\": [");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(methods, "        ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("],");
    _builder.newLine();
    {
      boolean _isEmpty = events.isEmpty();
      if (_isEmpty) {
        _builder.append("\"events\": []");
        _builder.newLine();
      } else {
        _builder.append("\"events\": [");
        _builder.newLine();
        _builder.append("            \t");
        _builder.append(events, "            \t");
        _builder.newLineIfNotEmpty();
        _builder.append("]");
        _builder.newLine();
      }
    }
    _builder.append("}");
    _builder.newLine();
    final String interfaceCode = _builder.toString();
    return interfaceCode;
  }
  
  public String defineEvents(final Contract contract) {
    return "";
  }
  
  public String defineMethods(final Contract contract) {
    int count = 0;
    int max = ((Object[])Conversions.unwrapArray(contract.getAttributes(), Object.class)).length;
    String methods = "";
    EList<Attribute> _attributes = contract.getAttributes();
    for (final Attribute attribute : _attributes) {
      {
        count++;
        final String attributeName = attribute.getName();
        final String attributeType = attribute.getType().toString();
        boolean _isModifiable = attribute.isModifiable();
        if (_isModifiable) {
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("{");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("\"name\": \"_value\",");
          _builder.newLine();
          _builder.append("    ");
          String _paramTypeForSolidity = this.getParamTypeForSolidity(attributeType);
          _builder.append(_paramTypeForSolidity, "    ");
          _builder.newLineIfNotEmpty();
          _builder.append("}");
          _builder.newLine();
          final String param = _builder.toString();
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("{");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("\"name\": \"set");
          String _capitalizeFirstLetter = this.capitalizeFirstLetter(attributeName);
          _builder_1.append(_capitalizeFirstLetter, "    ");
          _builder_1.append("\",");
          _builder_1.newLineIfNotEmpty();
          _builder_1.append("    ");
          _builder_1.append("\"description\": \"\",");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("\"params\": [");
          _builder_1.newLine();
          _builder_1.append("        ");
          _builder_1.append(param, "        ");
          _builder_1.newLineIfNotEmpty();
          _builder_1.append("    ");
          _builder_1.append("],");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("\"returns\": {}");
          _builder_1.newLine();
          _builder_1.append("},");
          _builder_1.newLine();
          final String methodCode = _builder_1.toString();
          String _methods = methods;
          methods = (_methods + methodCode);
        }
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("{");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("\"name\": \"get");
        String _capitalizeFirstLetter_1 = this.capitalizeFirstLetter(attributeName);
        _builder_2.append(_capitalizeFirstLetter_1, "    ");
        _builder_2.append("\",");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("\"description\": \"\",");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("\"params\": [],");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("\"returns\": {");
        _builder_2.newLine();
        _builder_2.append("        ");
        String _returnTypeForSolidity = this.getReturnTypeForSolidity(attributeType);
        _builder_2.append(_returnTypeForSolidity, "        ");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("},");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("\"details\": {");
        _builder_2.newLine();
        _builder_2.append("        ");
        _builder_2.append("\"stateMutability\": \"viewable\"");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("}");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.newLine();
        _builder_2.append("}");
        {
          if ((count < max)) {
            _builder_2.append(",");
          }
        }
        _builder_2.newLineIfNotEmpty();
        final String methodCode_1 = _builder_2.toString();
        String _methods_1 = methods;
        methods = (_methods_1 + methodCode_1);
      }
    }
    return methods;
  }
  
  public String getReturnTypeForSolidity(final String dataType) {
    if (dataType != null) {
      switch (dataType) {
        case "integer":
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("\"name\": \"output\",");
          _builder.newLine();
          _builder.append("\"schema\": {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("\"type\": \"integer\",");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("\"details\": {");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("\"type\": \"uint256\",");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("\"internalType\": \"uint256\"");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
          return _builder.toString();
        case "string":
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("\"name\": \"output\",");
          _builder_1.newLine();
          _builder_1.append("\"schema\": {");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("\"type\": \"string\"");
          _builder_1.newLine();
          _builder_1.append("}");
          _builder_1.newLine();
          return _builder_1.toString();
        case "boolean":
          StringConcatenation _builder_2 = new StringConcatenation();
          _builder_2.append("\"name\": \"output\",");
          _builder_2.newLine();
          _builder_2.append("\"schema\": {");
          _builder_2.newLine();
          _builder_2.append("    ");
          _builder_2.append("\"type\": \"boolean\"");
          _builder_2.newLine();
          _builder_2.append("}");
          _builder_2.newLine();
          return _builder_2.toString();
        case "address":
          StringConcatenation _builder_3 = new StringConcatenation();
          _builder_3.append("\"name\": \"output\",");
          _builder_3.newLine();
          _builder_3.append("\"schema\": {");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("\"type\": \"address\",");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("\"details\": {");
          _builder_3.newLine();
          _builder_3.append("        ");
          _builder_3.append("\"type\": \"address\",");
          _builder_3.newLine();
          _builder_3.append("        ");
          _builder_3.append("\"internalType\": \"address\",");
          _builder_3.newLine();
          _builder_3.append("        ");
          _builder_3.append("\"indexed\": false");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("}");
          _builder_3.newLine();
          _builder_3.append("}");
          _builder_3.newLine();
          return _builder_3.toString();
        case "array":
          StringConcatenation _builder_4 = new StringConcatenation();
          _builder_4.append("\"name\": \"output\",");
          _builder_4.newLine();
          _builder_4.append("\"schema\": {");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("\"type\": \"array\",");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("\"details\": {");
          _builder_4.newLine();
          _builder_4.append("        ");
          _builder_4.append("\"type\": \"uint256[]\",");
          _builder_4.newLine();
          _builder_4.append("        ");
          _builder_4.append("\"internalType\": \"uint256[]\"");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("}");
          _builder_4.newLine();
          _builder_4.append("}");
          _builder_4.newLine();
          return _builder_4.toString();
        default:
          StringConcatenation _builder_5 = new StringConcatenation();
          _builder_5.append("\"name\": \"output\",");
          _builder_5.newLine();
          _builder_5.append("\"schema\": {");
          _builder_5.newLine();
          _builder_5.append("    ");
          _builder_5.append("\"type\": \"integer\",");
          _builder_5.newLine();
          _builder_5.append("    ");
          _builder_5.append("\"details\": {");
          _builder_5.newLine();
          _builder_5.append("        ");
          _builder_5.append("\"type\": \"uint256\",");
          _builder_5.newLine();
          _builder_5.append("        ");
          _builder_5.append("\"internalType\": \"uint256\"");
          _builder_5.newLine();
          _builder_5.append("    ");
          _builder_5.append("}");
          _builder_5.newLine();
          _builder_5.append("}");
          _builder_5.newLine();
          return _builder_5.toString();
      }
    } else {
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("\"name\": \"output\",");
      _builder_5.newLine();
      _builder_5.append("\"schema\": {");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("\"type\": \"integer\",");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("\"details\": {");
      _builder_5.newLine();
      _builder_5.append("        ");
      _builder_5.append("\"type\": \"uint256\",");
      _builder_5.newLine();
      _builder_5.append("        ");
      _builder_5.append("\"internalType\": \"uint256\"");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("}");
      _builder_5.newLine();
      _builder_5.append("}");
      _builder_5.newLine();
      return _builder_5.toString();
    }
  }
  
  public String getParamTypeForSolidity(final String dataType) {
    if (dataType != null) {
      switch (dataType) {
        case "integer":
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("\"schema\": {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("\"type\": \"integer\",");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("\"details\": {");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("\"type\": \"uint256\",");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("\"internalType\": \"uint256\"");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
          return _builder.toString();
        case "string":
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("\"schema\": {");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("\"type\": \"string\",");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("\"details\": {");
          _builder_1.newLine();
          _builder_1.append("        ");
          _builder_1.append("\"type\": \"string memory\",");
          _builder_1.newLine();
          _builder_1.append("        ");
          _builder_1.append("\"internalType\": \"string memory\"");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("}");
          _builder_1.newLine();
          _builder_1.append("}");
          _builder_1.newLine();
          return _builder_1.toString();
        case "boolean":
          StringConcatenation _builder_2 = new StringConcatenation();
          _builder_2.append("\"schema\": {");
          _builder_2.newLine();
          _builder_2.append("    ");
          _builder_2.append("\"type\": \"boolean\"");
          _builder_2.newLine();
          _builder_2.append("}");
          _builder_2.newLine();
          return _builder_2.toString();
        case "address":
          StringConcatenation _builder_3 = new StringConcatenation();
          _builder_3.append("\"schema\": {");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("\"type\": \"address\",");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("\"details\": {");
          _builder_3.newLine();
          _builder_3.append("        ");
          _builder_3.append("\"type\": \"address\",");
          _builder_3.newLine();
          _builder_3.append("        ");
          _builder_3.append("\"internalType\": \"address\",");
          _builder_3.newLine();
          _builder_3.append("        ");
          _builder_3.append("\"indexed\": false");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("}");
          _builder_3.newLine();
          _builder_3.append("}");
          _builder_3.newLine();
          return _builder_3.toString();
        case "array":
          StringConcatenation _builder_4 = new StringConcatenation();
          _builder_4.append("\"schema\": {");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("\"type\": \"array\",");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("\"details\": {");
          _builder_4.newLine();
          _builder_4.append("        ");
          _builder_4.append("\"type\": \"uint256[]\",");
          _builder_4.newLine();
          _builder_4.append("        ");
          _builder_4.append("\"internalType\": \"uint256[]\"");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("}");
          _builder_4.newLine();
          _builder_4.append("}");
          _builder_4.newLine();
          return _builder_4.toString();
        default:
          StringConcatenation _builder_5 = new StringConcatenation();
          _builder_5.append("\"schema\": {");
          _builder_5.newLine();
          _builder_5.append("    ");
          _builder_5.append("\"type\": \"integer\",");
          _builder_5.newLine();
          _builder_5.append("    ");
          _builder_5.append("\"details\": {");
          _builder_5.newLine();
          _builder_5.append("        ");
          _builder_5.append("\"type\": \"uint256\",");
          _builder_5.newLine();
          _builder_5.append("        ");
          _builder_5.append("\"internalType\": \"uint256\"");
          _builder_5.newLine();
          _builder_5.append("    ");
          _builder_5.append("}");
          _builder_5.newLine();
          _builder_5.append("}");
          _builder_5.newLine();
          return _builder_5.toString();
      }
    } else {
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("\"schema\": {");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("\"type\": \"integer\",");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("\"details\": {");
      _builder_5.newLine();
      _builder_5.append("        ");
      _builder_5.append("\"type\": \"uint256\",");
      _builder_5.newLine();
      _builder_5.append("        ");
      _builder_5.append("\"internalType\": \"uint256\"");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("}");
      _builder_5.newLine();
      _builder_5.append("}");
      _builder_5.newLine();
      return _builder_5.toString();
    }
  }
  
  public String capitalizeFirstLetter(final String str) {
    String _upperCase = str.substring(0, 1).toUpperCase();
    String _substring = str.substring(1);
    return (_upperCase + _substring);
  }
}
