/*
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.ui;

import com.google.inject.Injector;
import lsi.us.es.mis.xtext.contract.ui.internal.ContractActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ContractExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ContractActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ContractActivator activator = ContractActivator.getInstance();
		return activator != null ? activator.getInjector(ContractActivator.LSI_US_ES_MIS_XTEXT_CONTRACT) : null;
	}

}
