/**
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.contract;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see lsi.us.es.mis.xtext.contract.ContractFactory
 * @model kind="package"
 * @generated
 */
public interface ContractPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "contract";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.us.lsi/es/mis/xtext/Contract";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "contract";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ContractPackage eINSTANCE = lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl.init();

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.ContractImpl <em>Contract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.ContractImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getContract()
   * @generated
   */
  int CONTRACT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__NAME = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__VERSION = 1;

  /**
   * The feature id for the '<em><b>Has Receive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__HAS_RECEIVE = 2;

  /**
   * The feature id for the '<em><b>Ownership</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__OWNERSHIP = 3;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__ATTRIBUTES = 4;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__EVENTS = 5;

  /**
   * The feature id for the '<em><b>Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__METHODS = 6;

  /**
   * The feature id for the '<em><b>Validators</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__VALIDATORS = 7;

  /**
   * The feature id for the '<em><b>Data Stores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__DATA_STORES = 8;

  /**
   * The number of structural features of the '<em>Contract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.AttributeImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 1;

  /**
   * The feature id for the '<em><b>Modifiable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__MODIFIABLE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.ValidatorImpl <em>Validator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.ValidatorImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getValidator()
   * @generated
   */
  int VALIDATOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATOR__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATOR__MESSAGE = 2;

  /**
   * The feature id for the '<em><b>Validation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATOR__VALIDATION = 3;

  /**
   * The number of structural features of the '<em>Validator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.MethodImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Statemutability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__STATEMUTABILITY = 2;

  /**
   * The feature id for the '<em><b>Outputs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__OUTPUTS = 3;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Validators</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__VALIDATORS = 5;

  /**
   * The feature id for the '<em><b>Events</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__EVENTS = 6;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.EventImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DESCRIPTION = 2;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.ParamImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getParam()
   * @generated
   */
  int PARAM = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__TYPE = 1;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.impl.DataStoreImpl <em>Data Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.impl.DataStoreImpl
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getDataStore()
   * @generated
   */
  int DATA_STORE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_STORE__NAME = 0;

  /**
   * The feature id for the '<em><b>From Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_STORE__FROM_TYPE = 1;

  /**
   * The feature id for the '<em><b>To Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_STORE__TO_TYPE = 2;

  /**
   * The number of structural features of the '<em>Data Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_STORE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.contract.DataType <em>Data Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.contract.DataType
   * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 7;


  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.Contract <em>Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contract</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract
   * @generated
   */
  EClass getContract();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Contract#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getName()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Name();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Contract#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getVersion()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Version();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Contract#isHasReceive <em>Has Receive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Receive</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#isHasReceive()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_HasReceive();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Contract#isOwnership <em>Ownership</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ownership</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#isOwnership()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Ownership();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Contract#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getAttributes()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Contract#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getEvents()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Events();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Contract#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methods</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getMethods()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Methods();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Contract#getValidators <em>Validators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Validators</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getValidators()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Validators();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Contract#getDataStores <em>Data Stores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data Stores</em>'.
   * @see lsi.us.es.mis.xtext.contract.Contract#getDataStores()
   * @see #getContract()
   * @generated
   */
  EReference getContract_DataStores();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see lsi.us.es.mis.xtext.contract.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Attribute#isModifiable <em>Modifiable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Modifiable</em>'.
   * @see lsi.us.es.mis.xtext.contract.Attribute#isModifiable()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Modifiable();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see lsi.us.es.mis.xtext.contract.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Type();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.Validator <em>Validator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Validator</em>'.
   * @see lsi.us.es.mis.xtext.contract.Validator
   * @generated
   */
  EClass getValidator();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Validator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.Validator#getName()
   * @see #getValidator()
   * @generated
   */
  EAttribute getValidator_Name();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Validator#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see lsi.us.es.mis.xtext.contract.Validator#getParams()
   * @see #getValidator()
   * @generated
   */
  EReference getValidator_Params();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Validator#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see lsi.us.es.mis.xtext.contract.Validator#getMessage()
   * @see #getValidator()
   * @generated
   */
  EAttribute getValidator_Message();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Validator#getValidation <em>Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Validation</em>'.
   * @see lsi.us.es.mis.xtext.contract.Validator#getValidation()
   * @see #getValidator()
   * @generated
   */
  EAttribute getValidator_Validation();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Method#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getName()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Name();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Method#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getParams()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Params();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Method#getStatemutability <em>Statemutability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Statemutability</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getStatemutability()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Statemutability();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Method#getOutputs <em>Outputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outputs</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getOutputs()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Outputs();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Method#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getDescription()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Description();

  /**
   * Returns the meta object for the reference list '{@link lsi.us.es.mis.xtext.contract.Method#getValidators <em>Validators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Validators</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getValidators()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Validators();

  /**
   * Returns the meta object for the reference list '{@link lsi.us.es.mis.xtext.contract.Method#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Events</em>'.
   * @see lsi.us.es.mis.xtext.contract.Method#getEvents()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Events();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see lsi.us.es.mis.xtext.contract.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.contract.Event#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see lsi.us.es.mis.xtext.contract.Event#getParams()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Params();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Event#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see lsi.us.es.mis.xtext.contract.Event#getDescription()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Description();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see lsi.us.es.mis.xtext.contract.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.Param#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see lsi.us.es.mis.xtext.contract.Param#getType()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Type();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.contract.DataStore <em>Data Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Store</em>'.
   * @see lsi.us.es.mis.xtext.contract.DataStore
   * @generated
   */
  EClass getDataStore();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.DataStore#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.contract.DataStore#getName()
   * @see #getDataStore()
   * @generated
   */
  EAttribute getDataStore_Name();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.DataStore#getFromType <em>From Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From Type</em>'.
   * @see lsi.us.es.mis.xtext.contract.DataStore#getFromType()
   * @see #getDataStore()
   * @generated
   */
  EAttribute getDataStore_FromType();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.contract.DataStore#getToType <em>To Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Type</em>'.
   * @see lsi.us.es.mis.xtext.contract.DataStore#getToType()
   * @see #getDataStore()
   * @generated
   */
  EAttribute getDataStore_ToType();

  /**
   * Returns the meta object for enum '{@link lsi.us.es.mis.xtext.contract.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Data Type</em>'.
   * @see lsi.us.es.mis.xtext.contract.DataType
   * @generated
   */
  EEnum getDataType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ContractFactory getContractFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.ContractImpl <em>Contract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.ContractImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getContract()
     * @generated
     */
    EClass CONTRACT = eINSTANCE.getContract();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__NAME = eINSTANCE.getContract_Name();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__VERSION = eINSTANCE.getContract_Version();

    /**
     * The meta object literal for the '<em><b>Has Receive</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__HAS_RECEIVE = eINSTANCE.getContract_HasReceive();

    /**
     * The meta object literal for the '<em><b>Ownership</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__OWNERSHIP = eINSTANCE.getContract_Ownership();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__ATTRIBUTES = eINSTANCE.getContract_Attributes();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__EVENTS = eINSTANCE.getContract_Events();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__METHODS = eINSTANCE.getContract_Methods();

    /**
     * The meta object literal for the '<em><b>Validators</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__VALIDATORS = eINSTANCE.getContract_Validators();

    /**
     * The meta object literal for the '<em><b>Data Stores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__DATA_STORES = eINSTANCE.getContract_DataStores();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.AttributeImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Modifiable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__MODIFIABLE = eINSTANCE.getAttribute_Modifiable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.ValidatorImpl <em>Validator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.ValidatorImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getValidator()
     * @generated
     */
    EClass VALIDATOR = eINSTANCE.getValidator();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATOR__NAME = eINSTANCE.getValidator_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALIDATOR__PARAMS = eINSTANCE.getValidator_Params();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATOR__MESSAGE = eINSTANCE.getValidator_Message();

    /**
     * The meta object literal for the '<em><b>Validation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATOR__VALIDATION = eINSTANCE.getValidator_Validation();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.MethodImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__NAME = eINSTANCE.getMethod_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__PARAMS = eINSTANCE.getMethod_Params();

    /**
     * The meta object literal for the '<em><b>Statemutability</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__STATEMUTABILITY = eINSTANCE.getMethod_Statemutability();

    /**
     * The meta object literal for the '<em><b>Outputs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__OUTPUTS = eINSTANCE.getMethod_Outputs();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__DESCRIPTION = eINSTANCE.getMethod_Description();

    /**
     * The meta object literal for the '<em><b>Validators</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__VALIDATORS = eINSTANCE.getMethod_Validators();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__EVENTS = eINSTANCE.getMethod_Events();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.EventImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__PARAMS = eINSTANCE.getEvent_Params();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__DESCRIPTION = eINSTANCE.getEvent_Description();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.ParamImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__TYPE = eINSTANCE.getParam_Type();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.impl.DataStoreImpl <em>Data Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.impl.DataStoreImpl
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getDataStore()
     * @generated
     */
    EClass DATA_STORE = eINSTANCE.getDataStore();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_STORE__NAME = eINSTANCE.getDataStore_Name();

    /**
     * The meta object literal for the '<em><b>From Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_STORE__FROM_TYPE = eINSTANCE.getDataStore_FromType();

    /**
     * The meta object literal for the '<em><b>To Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_STORE__TO_TYPE = eINSTANCE.getDataStore_ToType();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.contract.DataType <em>Data Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.contract.DataType
     * @see lsi.us.es.mis.xtext.contract.impl.ContractPackageImpl#getDataType()
     * @generated
     */
    EEnum DATA_TYPE = eINSTANCE.getDataType();

  }

} //ContractPackage
