/**
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.contract;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Method#getName <em>Name</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Method#getParams <em>Params</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Method#getStatemutability <em>Statemutability</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Method#getOutputs <em>Outputs</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Method#getDescription <em>Description</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Method#getModifiers <em>Modifiers</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod()
 * @model
 * @generated
 */
public interface Method extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.contract.Method#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.contract.Param}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod_Params()
   * @model containment="true"
   * @generated
   */
  EList<Param> getParams();

  /**
   * Returns the value of the '<em><b>Statemutability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statemutability</em>' attribute.
   * @see #setStatemutability(String)
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod_Statemutability()
   * @model
   * @generated
   */
  String getStatemutability();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.contract.Method#getStatemutability <em>Statemutability</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statemutability</em>' attribute.
   * @see #getStatemutability()
   * @generated
   */
  void setStatemutability(String value);

  /**
   * Returns the value of the '<em><b>Outputs</b></em>' containment reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.contract.Output}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outputs</em>' containment reference list.
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod_Outputs()
   * @model containment="true"
   * @generated
   */
  EList<Output> getOutputs();

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.contract.Method#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Modifiers</b></em>' reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.contract.Modifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifiers</em>' reference list.
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getMethod_Modifiers()
   * @model
   * @generated
   */
  EList<Modifier> getModifiers();

} // Method
