/**
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.contract;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Modifier#getName <em>Name</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Modifier#getParams <em>Params</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Modifier#getMessage <em>Message</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.contract.Modifier#getValidation <em>Validation</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.contract.ContractPackage#getModifier()
 * @model
 * @generated
 */
public interface Modifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getModifier_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.contract.Modifier#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.contract.Param}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getModifier_Params()
   * @model containment="true"
   * @generated
   */
  EList<Param> getParams();

  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getModifier_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.contract.Modifier#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

  /**
   * Returns the value of the '<em><b>Validation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Validation</em>' attribute.
   * @see #setValidation(String)
   * @see lsi.us.es.mis.xtext.contract.ContractPackage#getModifier_Validation()
   * @model
   * @generated
   */
  String getValidation();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.contract.Modifier#getValidation <em>Validation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Validation</em>' attribute.
   * @see #getValidation()
   * @generated
   */
  void setValidation(String value);

} // Modifier
