/*
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lsi.us.es.mis.xtext.ContractRuntimeModule;
import lsi.us.es.mis.xtext.ContractStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ContractIdeSetup extends ContractStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ContractRuntimeModule(), new ContractIdeModule()));
	}
	
}
